In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"C:\Users\Rishi kumar\Downloads\BlackFriday.csv")
del df['Product_Category_2']
del df['Product_Category_3']

In [2]:
df.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,7969


ANALYZE THE COLUMNS

In [4]:
#how many unique customer are there
df['User_ID'].nunique()

5891

In [6]:
#these are all the unique user id
df['User_ID'].unique()

array([1000001, 1000002, 1000003, ..., 1004113, 1005391, 1001529],
      shape=(5891,))

In [7]:
#how many unique product are there
df['Product_ID'].nunique()

3623

In [9]:
#value of gender
df['Gender'].unique()

<StringArray>
['F', 'M']
Length: 2, dtype: str

In [21]:
#how many unique age category are there
df['Age'].unique()

<StringArray>
['0-17', '55+', '26-35', '46-50', '51-55', '36-45', '18-25']
Length: 7, dtype: str

In [13]:
#how many unique occupation are there
df['Occupation'].unique()

array([10, 16, 15,  7, 20,  9,  1, 12, 17,  0,  3,  4, 11,  8, 19,  2, 18,
        5, 14, 13,  6])

In [15]:
#how many unique city category are there
df['City_Category'].unique()

<StringArray>
['A', 'C', 'B']
Length: 3, dtype: str

In [16]:
#how many unique  Stay_In_Current_City_Years are there
df['Stay_In_Current_City_Years'].unique()

<StringArray>
['2', '4+', '3', '1', '0']
Length: 5, dtype: str

In [17]:
df['Marital_Status'].unique()

array([0, 1])

In [18]:
#how many unique product category
df['Product_Category_1'].unique()

array([ 3,  1, 12,  8,  5,  4,  2,  6, 14, 11, 13, 15,  7, 16, 18, 10, 17,
        9])

In [19]:
#total money
df['Purchase'].sum()

np.int64(5017668378)

In [20]:
#average
df['Purchase'].sum()/len(df['Purchase'])

np.float64(9333.859852635065)

In [22]:
df.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Purchase'],
      dtype='str')

In [23]:
for column in df.columns:
    print(column, ":", df[column].nunique())

User_ID : 5891
Product_ID : 3623
Gender : 2
Age : 7
Occupation : 21
City_Category : 3
Stay_In_Current_City_Years : 5
Marital_Status : 2
Product_Category_1 : 18
Purchase : 17959


In [ ]:
#We focus on key columns like Gender, Age, Marital_Status, Product_Category and Purchase.
#We handle missing data by dropping columns that are too sparse, like Product_Category_2 and Product_Category_3.
#We focus on understanding the unique values in various columns to gain an overview of the data. Specifically, we used unique() and nunique() functions to extract meaningful information from individual columns.